server:
  port: ${APP_PORT:8080}

management:
  server.port: ${MONITORING_PORT:8081}

spring:
  jackson:
    default-property-inclusion: ${JACKSON_DEFAULT_PROPERTY_INCLUSION:non_null}
    deserialization:
      fail_on_unknown_properties: ${JACKSON_DESERIALIZATION_FAIL_ON_UNKNOWN_PROPERTIES:false}
    serialization:
      fail_on_empty_beans: ${JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS:false}
      write_dates_as_timestamps: ${JACKSON_SERIALIZATION_WRITE_DATES_AS_TIMESTAMPS:false}
    property-naming-strategy: ${JACKSON_PROPERTY_NAMING_STRATEGY:SNAKE_CASE}
