logging:
  level:
    io.r2dbc.postgresql.PARAM: ${LOGGING_R2DBC_PARAM_LEVEL:INFO}
    org:
      springframework:
        r2dbc: ${LOGGING_R2DBC_LEVEL:INFO}
  file:
    name: ${LOGGING_FILE_NAME:application.log}
