server:
  port: 8090

management:
  server.port: 8091

logging:
  level:
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    org:
      springframework:
        r2dbc: DEBUG
  file:
    path: tmp/logs
    name: application.log
